### ISSUE TITLE
Соблюдение новых ограничений на длительность запросов

### ISSUE THREAD

**Issue by Helow19274** [leshchenko1979/fast_bitrix24#187]
Совсем недавно в облачной версии Б24 добавили новые лимиты запросов: https://helpdesk.bitrix24.ru/open/15959788
Сейчас это никак не отслеживается библиотекой, даже если установить respect_velocity_policy на True

**Comment by leshchenko1979** [comment]
Спасибо! Вам сейчас это сильно мешает?

**Comment by Helow19274** [comment]
Нет, сейчас не мешает, но если вы это добавите, будет полезно) Пока что у нас не так много ёмких запросов

**Comment by leshchenko1979** [comment]
Разработчики пишут, что отказы из-за описанного лимита возникают крайне редко: https://t.me/bitrix24apps/14038

**Comment by Helow19274** [comment]
![image](https://user-images.githubusercontent.com/20171143/177500217-f22c49c4-91fc-48ea-b015-0b515f532373.png)
Опять встретился с этой ошибкой, хотя сейчас не было похоже, что мы битрикс сильно нагружали

**Comment by badigit** [comment]
Проблема очень актуальна, при обновлении сущностей возникает после обновления  примерно 1000+ сущностей.
 90%|███████████████████████████████████████████████████████████████████████████████████████████████▍          | 900/1000 [00:19<00:02, 46.05it/s]
Traceback (most recent call last):
  File "fast_bitrix_mass_update.py", line 32, in <module>
    b.call('crm.item.update', tasks)
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\bitrix.py", line 234, in sync_wrapper
    return loop.run_until_complete(coroutine(*args, **kwargs))
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\logger.py", line 11, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\bitrix.py", line 168, in call
    return await self.srh.run_async(request_cls(self, method, items).run())
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\srh.py", line 101, in run_async
    return await coroutine
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\user_request.py", line 262, in run
    get_by_ID=False,
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\mult_request.py", line 65, in run
    extracted_len = self.process_done_tasks(done)
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\mult_request.py", line 94, in process_done_tasks
    done_task.result(), self.get_by_ID
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\server_response.py", line 43, in extract_results
    self.raise_for_errors()
  File "C:\Users\Dee\AppData\Local\Programs\Python\Python37\lib\site-packages\fast_bitrix24\server_response.py", line 56, in raise_for_errors
    raise ErrorInServerResponseException(errors)
fast_bitrix24.server_response.ErrorInServerResponseException: {'order0000000549': {'error': 'OPERATION_TIME_LIMIT', 'error_description': 'Method is blocked due to operation time limit.'}}

Попробую конечно что нибудь придумать, но моих знаний не хватает чтобы это корректно обрабатывать

**Comment by zznobzz** [comment]
Постоянно ловлю ошибку при попытке вытянуть методом list_and_get сделки. Общее количество сделок около 70 000.
В среднем падает 21 000.

**Comment by leshchenko1979** [comment]
Сейчас при отправке батчей на сервер время исполнения учитывается по методу "batch".

При этом сообщения об ошибке продолжают приходить.

На самом деле нужно учитывать время исполнения раздельно по каждому методу, используемому внутри батча.

**Comment by badigit** [comment]
Также можно иметь в виду что минимальное фиксируемое значение исполнения 0.1 сек.
Время выполнения методов с меньшим значением не фиксируется в operating. 

Не зная этого, можно при тестах долго одуплять, почему запросы идут а значение не меняется.
