### ISSUE TITLE
Ошибка при использовании get_all для метода socialnetwork.api.workgroup.list

### ISSUE THREAD

**Issue by dany-falta** [leshchenko1979/fast_bitrix24#207]
Exception has occurred: ViolationError
```File C:\Program Files\Python39\lib\site-packages\fast_bitrix24\user_request.py, line 145 in GetAllUserRequest:
isinstance(self.results, list):
isinstance(self.results, list) was False
self was <fast_bitrix24.user_request.GetAllUserRequest object at 0x000001D5F3CAB280>
self.results was {'workgroups': [{'id': '8'}, {'id': '10'}, {'id': '12'}, {'id': '14'}, {'id': '16'}, {'id': '18'}, {'id': '20'}, {'id': '22'}, {'id': '24'}, {'id': '26'}, {'id': '28'}, {'id': '30'}, {'id': '32'}, {'id': '34'}, {'id': '36'}, {'id': '38'}, {'id': '40'}, {'id': '42'}, {'id': '44'}, {'id': '46'}, {'id': '48'}, {'id': '50'}, {'id': '52'}, {'id': '54'}, {'id': '58'}, {'id': '60'}, {'id': '62'}, {'id': '64'}, {'id': '66'}, {'id': '68'}, {'id': '70'}, {'id': '72'}, {'id': '73'}, {'id': '74'}, {'id': '76'}, {'id': '78'}, {'id': '80'}, {'id': '82'}, {'id': '83'}, {'id': '85'}, {'id': '87'}, {'id': '89'}, {'id': '91'}, {'id': '93'}, {'id': '95'}, {'id': '97'}, {'id': '99'}, {'id': '101'}, {'id': '103'}, {'id': '105'}]}
  File "D:\Dani Files\Documents\Py_projects\main.py", line 6, in <module>
    res = b.get_all(```

**Comment by leshchenko1979** [comment]
Пришлите лог, пожалуйста

**Comment by dany-falta** [comment]
> Пришлите лог, пожалуйста

```ERROR:root:File C:\Program Files\Python39\lib\site-packages\fast_bitrix24\user_request.py, line 145 in GetAllUserRequest:
isinstance(self.results, list):
isinstance(self.results, list) was False
self was <fast_bitrix24.user_request.GetAllUserRequest object at 0x0000019BB7C6DD60>
self.results was {'workgroups': [{'id': '8'}, {'id': '10'}, {'id': '12'}, {'id': '14'}, {'id': '16'}, {'id': '18'}, {'id': '20'}, {'id': '22'}, {'id': '24'}, {'id': '26'}, {'id': '28'}, {'id': '30'}, {'id': '32'}, {'id': '34'}, {'id': '36'}, {'id': '38'}, {'id': '40'}, {'id': '42'}, {'id': '44'}, {'id': '46'}, {'id': '48'}, {'id': '50'}, {'id': '52'}, {'id': '54'}, {'id': '58'}, {'id': '60'}, {'id': '62'}, {'id': '64'}, {'id': '66'}, {'id': '68'}, {'id': '70'}, {'id': '72'}, {'id': '73'}, {'id': '74'}, {'id': '76'}, {'id': '78'}, {'id': '80'}, {'id': '82'}, {'id': '83'}, {'id': '85'}, {'id': '87'}, {'id': '89'}, {'id': '91'}, {'id': '93'}, {'id': '95'}, {'id': '97'}, {'id': '99'}, {'id': '101'}, {'id': '103'}, {'id': '105'}]}
Traceback (most recent call last):
  File "d:\Dani Files\Documents\Py_projects\main.py", line 9, in <module>
    res = b.get_all(
  File "C:\Program Files\Python39\lib\site-packages\fast_bitrix24\bitrix.py", line 234, in sync_wrapper
    return loop.run_until_complete(coroutine(*args, **kwargs))
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Program Files\Python39\lib\site-packages\fast_bitrix24\logger.py", line 11, in wrapper
    return await func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\fast_bitrix24\bitrix.py", line 72, in get_all
    return await self.srh.run_async(GetAllUserRequest(self, method, params).run())
  File "C:\Program Files\Python39\lib\site-packages\fast_bitrix24\srh.py", line 101, in run_async
    return await coroutine
  File "C:\Program Files\Python39\lib\site-packages\fast_bitrix24\user_request.py", line 115, in run
    await self.make_remaining_requests()
  File "C:\Program Files\Python39\lib\site-packages\icontract\_checkers.py", line 577, in wrapper
    raise violation_error
icontract.errors.ViolationError: File C:\Program Files\Python39\lib\site-packages\fast_bitrix24\user_request.py, line 145 in GetAllUserRequest:
isinstance(self.results, list):
isinstance(self.results, list) was False
self was <fast_bitrix24.user_request.GetAllUserRequest object at 0x0000019BB7C6DD60>
self.results was {'workgroups': [{'id': '8'}, {'id': '10'}, {'id': '12'}, {'id': '14'}, {'id': '16'}, {'id': '18'}, {'id': '20'}, {'id': '22'}, {'id': '24'}, {'id': '26'}, {'id': '28'}, {'id': '30'}, {'id': '32'}, {'id': '34'}, {'id': '36'}, {'id': '38'}, {'id': '40'}, {'id': '42'}, {'id': '44'}, {'id': '46'}, {'id': '48'}, {'id': '50'}, {'id': '52'}, {'id': '54'}, {'id': '58'}, {'id': '60'}, {'id': '62'}, {'id': '64'}, {'id': '66'}, {'id': '68'}, {'id': '70'}, {'id': '72'}, {'id': '73'}, {'id': '74'}, {'id': '76'}, {'id': '78'}, {'id': '80'}, {'id': '82'}, {'id': '83'}, {'id': '85'}, {'id': '87'}, {'id': '89'}, {'id': '91'}, {'id': '93'}, {'id': '95'}, {'id': '97'}, {'id': '99'}, {'id': '101'}, {'id': '103'}, {'id': '105'}]}```

**Comment by leshchenko1979** [comment]
Чтобы получить логи, нужно добавить в начало вашего скрипта:

import logging

logging.getLogger('fast_bitrix24').addHandler(logging.StreamHandler())

**Comment by dka58** [comment]
> Чтобы получить логи, нужно добавить в начало вашего скрипта:
> 
> import logging
> 
> logging.getLogger('fast_bitrix24').addHandler(logging.StreamHandler())

Здравствуйте.  Лог ошибки

```
Starting get_all((<fast_bitrix24.bitrix.Bitrix object at 0x000001F6411CCFD0>, 'socialnetwork.api.workgroup.list', {'select': ['ID', 'NAME', 'DESCRIPTION', 'DATE_CREATE', 'DATE_UPDATE', 'DATE_ACTIVITY', 'SUBJECT_ID', 'KEYWORDS', 'IMAGE_ID', 'NUMBER_OF_MEMBERS', 'INITIATE_PERMS', 'SPAM_PERMS', 'SUBJECT_NAME']}), {})
Requesting {'method': socialnetwork.api.workgroup.list, 'params': {'select': ['ID', 'NAME', 'DESCRIPTION', 'DATE_CREATE', 'DATE_UPDATE', 'DATE_ACTIVITY', 'SUBJECT_ID', 'KEYWORDS', 'IMAGE_ID', 'NUMBER_OF_MEMBERS', 'INITIATE_PERMS', 'SPAM_PERMS', 'SUBJECT_NAME'], 'order': {'ID': 'ASC'}}}
Response: {'result': {'workgroups': [{РЕЗУЛЬТАТ БЫЛ ТУТ}]}, 'next': 50, 'total': 201, 'time': {'start': 1667156327.84961, 'finish': 1667156327.884964, 'duration': 0.035353899002075195, 'processing': 0.010620832443237305, 'date_start': '2022-10-30T21:58:47+03:00', 'date_finish': '2022-10-30T21:58:47+03:00', 'operating_reset_at': 1667156927, 'operating': 0}}
File C:\Program Files\Python39\lib\site-packages\fast_bitrix24\user_request.py, line 145 in GetAllUserRequest:
isinstance(self.results, list):
isinstance(self.results, list) was False
self was <fast_bitrix24.user_request.GetAllUserRequest object at 0x000001F6423D85B0>
self.results was {'workgroups': [{РЕЗУЛЬТАТ БЫЛ ТУТ}]}
```

**Comment by leshchenko1979** [comment]
Нужен полный лог, как его выдавала система, без изменений
