### ISSUE TITLE
Ошибка с async_playwright

### ISSUE THREAD

**Issue by Verifierz** [leshchenko1979/fast_bitrix24#208]
При подключении модуля from fast_bitrix24 import Bitrix
с подключенным from playwright.async_api import async_playwright
Получаю ошибку
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Connection.run() done, defined at C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py:217> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 224, in run
    await self._transport.connect()
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_transport.py", line 121, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "c:\VSProject\OF\pw_testing.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\VSProject\OF\pw_testing.py", line 11, in main
    async with async_playwright() as playwright:
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_transport.py", line 121, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec    
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pressure\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by leshchenko1979** [comment]
Не могу понять, почему вы считаете, что это проблема моей либы

**Comment by sazynek** [comment]
Комментарий для будущих поколений). В редакторе кода прокликайте по class'y  Bitrix или `BitrixAsync`. Вас перебросит по ссылке вида: venv/Lib/site-packages/fast_bitrix24/bitrix.py.  Там в import найдите строчку `from . import correct_asyncio`. Можете просто её закомментировать, как сделал я и всё заработает или же провалиться в папку и там изменить `asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`. Тут уже стоит обратиться к документации asyncio.

**Comment by leshchenko1979** [comment]
@sazynek Спасибо, уберу это из библиотеки
