### ISSUE TITLE
Ошибка при работе с Django

### ISSUE THREAD

**Issue by csn18** [leshchenko1979/fast_bitrix24#211]
Django 4.0

Следующий код
```
from fast_bitrix24 import Bitrix


def send_request_bitrix():
    webhook = "https://название_компании.bitrix24.ru/rest/22/тут_токен/"
    b = Bitrix(webhook)
    print(b)
    
    
def index(request):
    send_request_bitrix()
    return render(request, 'pages/index.html', locals())
 ```

При заходе на страницу получаю вот такую ошибку.
```
Traceback (most recent call last):
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/forest/Desktop/repo/helpsypro/app/views.py", line 95, in index
    send_request_bitrix()
  File "/Users/forest/Desktop/repo/helpsypro/app/views.py", line 88, in send_request_bitrix
    BitrixConnector = Bitrix(webhook, verbose=False,
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/fast_bitrix24/bitrix.py", line 49, in __init__
    self.srh = ServerRequestHandler(webhook, respect_velocity_policy, client)
  File "/Users/forest/Library/Caches/pypoetry/virtualenvs/psycon-6e8C299w-py3.9/lib/python3.9/site-packages/fast_bitrix24/srh.py", line 73, in __init__
    self.request_complete = Event()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/locks.py", line 177, in __init__
    self._loop = events.get_event_loop()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
```

В чем может быть проблема?

**Comment by leshchenko1979** [comment]
Дубль #204
