### ISSUE TITLE
AttributeError: 'GetByIDUserRequest' object has no attribute 'ID_list'

### ISSUE THREAD

**Issue by leshchenko1979** [leshchenko1979/fast_bitrix24#55]
```
df = pd.read_excel('./sources/new_contacts.xlsx', usecols=['Contact External ID'], engine='openpyxl')
    ID_LIST = list(map(int, df['Contact External ID'].values))  #  - exists

    bx_eu_root.get_by_ID('crm.timeline.comment.list', ID_LIST, params={'filter': {'ENTITY_TYPE': 'contact'}})

Traceback (most recent call last):
  File "C:/Users/karpo/Python/salesforce_supporter/crm/bitrix/eu/get_comments_contacts.py", line 92, in <module>
    bx_eu_root.get_by_ID('crm.timeline.comment.list', ID_LIST, params={'filter': {'ENTITY_TYPE': 'contact'}})
  File "C:\Users\karpo\Python\salesforce_supporter\venv\lib\site-packages\fast_bitrix24\bitrix.py", line 84, in get_by_ID
    return self.srh.run(GetByIDUserRequest(self.srh, method, params, ID_list, ID_field_name).run())
  File "C:\Users\karpo\Python\salesforce_supporter\venv\lib\site-packages\fast_bitrix24\user_request.py", line 133, in init
    super().init(srh, method, params)
  File "C:\Users\karpo\Python\salesforce_supporter\venv\lib\site-packages\fast_bitrix24\user_request.py", line 18, in init
    self.check_special_limitations()
  File "C:\Users\karpo\Python\salesforce_supporter\venv\lib\site-packages\fast_bitrix24\user_request.py", line 143, in check_special_limitations
    if not(isinstance(self.ID_list, Sequence)):
AttributeError: 'GetByIDUserRequest' object has no attribute 'ID_list'

Process finished with exit code 1
```

reported by @sharmankin

**Comment by leshchenko1979** [comment]
fixed
